### ISSUE TITLE
Timeline for Nanjing JS conf

### ISSUE THREAD

**Issue by cocoyu** [jsconfcn/ningjs#3]
**Deadlines**

**1. March.31** Website Design @Jan

**2. mid May**  
- [ ] Sponsors (1need to design different sponsor packages (2 looking for f&b sponsors as well (3 sponsors can send 1 speaker from their side @Thomas
- [ ] Venue @echo&@alexia please help with that part
- [ ] Speakers  (1Can someone give a speech representing Wiredcraft @xeodou (2 everyone please suggest potential candidates
- [ ] make a promotion video for 2mins

**3. Jun.1st** 
- [ ] online early bird ticket sale/ group ticket sale
- [ ] start to reach out to media & promote on social media 

**4. Jul.1st**
- [ ] Logistic
- [ ] T-shirt, brochures, welcome bags, sponsor tables, venue setup&decoration, etc

**Comment by Alexia** [comment]
What am I tagged on this?

**Comment by longtian** [comment]
:+1:

**Comment by quentinberder** [comment]
@Alexia it was a mistake, one of our colleague has a nickname very similar. Sorry for this.

**Comment by atian25** [comment]
先报个名,  「EGG - 企业级 Web 基础 Node 框架」 by 阿里 Node 工作组 (讲师待定)

@fengmk2

**Comment by fengmk2** [comment]
@atian25 赞！阿里积累多年的 nodejs web 框架也会在最近几个月正式开源。

**Comment by cocoyu** [comment]
@atian25 好的

**Comment by SFantasy** [comment]
@fengmk2 就叫 EGG 么，哈哈哈 :smile:

**Comment by ngot** [comment]
报个名 《912亿背后的Node.js》 By 天猫Node小组，讲师@庄少

**Comment by cocoyu** [comment]
@atian25 @ngot 收到！我们的网站还在建设中，4月初应该可以上线了。 到时有个简单在线讲师申请表单需要你们填写哦~

**Comment by iamroody** [comment]
赞，2016 jsconf 终于开始了，预祝顺利～

**Comment by wulingying** [comment]
赞，ningjs

**Comment by XadillaX** [comment]
去年因为台风没去成 :joy_cat:

**Comment by XadillaX** [comment]
@atian25 egg 早有耳闻 233333

**Comment by xeodou** [comment]
@XadillaX 今年我们定在台风季后

**Comment by fengmk2** [comment]
@atian25 可以去填表了。

**Comment by DavidCai1111** [comment]
👍 好多关于 node 的演讲，赞~

**Comment by cocoyu** [comment]
大家快推荐讲师和赞助商啊~ @jsconfcn/jingjs

**Comment by wssgcg1213** [comment]
It's June 3rd. 
When selling tickets?

**Comment by xeodou** [comment]
Hi @wssgcg1213  ,  Tickets will available from next week Wednesday noon, June 8th.

**Comment by Suixinlei** [comment]
今年应该没有台风了

**Comment by XadillaX** [comment]
已抢早鸟。

**Comment by FrankFang** [comment]
@XadillaX 怎么抢

**Comment by xeodou** [comment]
closing
